feat:add page
Dolka84/Lubimovka pull request #2
Opened 2022-06-02 20:49 UTC by zigfrei

Посмотрите стили page и body, если норм то запушу

2022-06-02 21:06 UTC, Dolka84 commented
Вроде все ок

2022-06-03 16:00 UTC, Stern-Ritter requested changes
Добавил несколько моментов, которые по моему мнению нужно поправить и можно делать merge :)

2022-06-03 16:00 UTC, Stern-Ritter commented on blocks/page/page.css
> +  min-width: 414px;
Тут точно не 414px а 320px, проговаривали на брифинге. Минимальная ширина должна быть 320px, просто макет у нас есть только для 414px мобильной версии, придется немного с этим помучаться.

2022-06-03 16:00 UTC, Stern-Ritter commented on index.html
> +  <link rel="stylesheet" href="pages/index.css">
Всегда лучше использовать относительные пути мне кажется: href="./pages/index.css"

2022-06-03 16:00 UTC, Stern-Ritter commented on index.html
> +  <script src="./scripts/index.js"></script>
Добавь, пожалуйста, <script **type="module"** src="./scripts/index.js"></script> чтобы можно было в index.js делать импорты типа таких: 
```
import {
  enableValidation
} from './components/validate.js'; 
```
и каждый мог реализовать свою часть в отдельном js файле и потом импортировать в index.js.

2022-06-03 16:03 UTC, zigfrei commented on blocks/page/page.css
> +  min-width: 414px;
+

2022-06-03 16:04 UTC, zigfrei commented on index.html
> +  <link rel="stylesheet" href="pages/index.css">
ок

2022-06-03 16:04 UTC, zigfrei commented on index.html
> +  <script src="./scripts/index.js"></script>
А вот это хорошо)) добавил

2022-06-03 16:14 UTC, Stern-Ritter approved these changes

2022-06-03 16:17 UTC, merged