Feat/card
Dolka84/Lubimovka pull request #9
Opened 2022-06-07 22:23 UTC by IIKolchin

2022-06-08 11:58 UTC, Stern-Ritter requested changes

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +      <section class="card">
Это явно не section отдельная, а скорее элемент card, который можно переиспользовать в разных секциях я бы сделал div -ом.

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/card.css
> +  padding: 0;
Эти стили не нужны, потому что вряд ли у карточки всегда будет 100% width родителя, внешних отступов (margin) у нее тоже не должно быть. Не совсем понял зачем padding: 0; (ведь он вроде и так 0), но его тоже не должно быть :)

2022-06-08 11:58 UTC, Stern-Ritter commented on pages/index.css
> +@import url(../blocks/card/__title/card__title.css);
Мне кажется всегда лучше когда стили подключаются в той же последовательности, в которой блоки с этими стилями располагаются в html, так title встречает раньше всего и должен идти сразу после /card.css Но это лично мое мнение, просто сложно когда все вперемешку идет. :)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__title/card__title.css
> +  padding: 0;
Зачем padding: 0, он же и так 0 по-умолчанию у div ?)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__title/card__title.css
> +  padding: 0;
Зачем padding: 0, он же и так 0 по-умолчанию у div ?)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__title/card__title.css
> +  height: 300px;
А зачем жестко ограничиваешь высоту, можно же min-height: 300px; ?)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__title/card__title.css
> +  height: 300px;
А зачем жестко ограничиваешь высоту, можно же min-height: 300px; ?)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__title/card__title.css
> +  cursor: pointer;
Не помню было ли ли это в брифе, но зачем вешать cursor: pointer на весь блок, если кликабельны только всплывающие кнопки, это вводит в заблуждение: кажется что должно что-то происходить при нажатии и на саму карточку, хотя если так прописано в брифе то нет вопросов)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__title/card__title.css
> +  cursor: pointer;
Не помню было ли ли это в stylebook, а зачем вешать cursor: pointer на весь блок, если кликабельны только всплывающие кнопки, мне кажется это вводив в заблуждение, хотя если так прописано в брифе то нет вопросов)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__text/card__text.css
> +  display: block;
h3 же и так имеет свойство display: block; по-умолчанию)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__text/card__text.css
> +  display: block;
h3 же и так имеет свойство display: block; по-умолчанию)

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +            class="card__button card__button_download card__button_hover"
href="#" чтобы при нажатии на ссылку страница не перезагружалась) https://qna.habr.com/q/240696

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__button/card__button.css
> +  margin: 0;
Не понимаю зачем это) Они и так 0

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +            href=""
Наверное все-таки лучше  href="#", чтобы странице при клике не перезагружалась)

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +            href=""
Наверное все-таки лучше  href="#", чтобы странице при клике не перезагружалась)

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +            <span class="card__button card__button_look-span"></span>
Не понимаю почему у ссылки и у span внутри нее одинаковый класс)
Вообще, мне кажется реализация, для которой для каждой кнопки необходимо делать две svg картинки мягко говоря не оптимальна)

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +            <span class="card__button card__button_look-span"></span>
Не понимаю почему у ссылки и у span внутри нее одинаковый класс)
Вообще, мне кажется реализация, для которой для каждой кнопки необходимо делать две svg картинки мягко говоря не оптимальна)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__author/card__author.css
> +font-family: 'Neue Machina', sans-serif;
Форматирование отступов поехало)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__author/card__author.css
> +font-family: 'Neue Machina', sans-serif;
Форматирование поехало)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__author/card__author.css
> +  background: #ecece5;
По-моему он прозрачный должен быть) это цвет самой страницы

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__author/card__author.css
> +  background: #ecece5;
По-моему он прозрачный должен быть) это цвет самой страницы

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__location/card__location.css
> +  display: block;
p и так display: block

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__location/card__location.css
> +  display: block;
p и так display: block

2022-06-08 11:58 UTC, Stern-Ritter commented on scripts/index.js
> +];
Лучше вынести в отдельный js файл и сделать оттуда импорт)

2022-06-08 11:58 UTC, Stern-Ritter commented on scripts/index.js
> +];
Лучше вынести в отдельный js файл и сделать оттуда импорт)

2022-06-08 11:58 UTC, Stern-Ritter commented on scripts/index.js
> +
Функцию тоже можно вынести в отдельный файл и импортировать)

2022-06-08 11:58 UTC, Stern-Ritter commented on scripts/index.js
> +
Тоже можно вынести в отдельный файл и импортировать)

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__author-name/card__author-name.css
> +  line-height: 24px;
line-height везде лучше указывать в относительном выражении, тут например будет line-height: 1.2 )

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__author-name/card__author-name.css
> +  line-height: 24px;
line-height везде лучше указывать в относительном выражении, тут например будет line-height: 1.2 )

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__button/card__button.css
> +  margin: 0;
Не понимаю зачем это) Они и так 0

2022-06-08 11:58 UTC, Stern-Ritter commented on blocks/card/__button/card__button.css
> +  margin: 0;
Не понимаю зачем это) Они и так 0

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +          <h3 class="card__text">С_училища</h3>
По stylebook это не h3, а h7

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +          <h3 class="card__text">С_училища</h3>
По stylebook это не h3, а h7

2022-06-08 11:58 UTC, Stern-Ritter commented on pages/index.css
> +@import url(../blocks/card/__look/card__look.css);
В консоли ругается, что такого файла нет

2022-06-08 11:58 UTC, Stern-Ritter commented on pages/index.css
> +@import url(../blocks/card/__look/card__look.css);
В консоли ругается, что такого файла нет

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +        <h2 class="photo__title">Заголовок блока с фотографиями</h2>
Наверное лучше не разрывный пробел поставить чтобы было как в макете с переносом 
`<h2 class="photo__title">Заголовок блока с&nbsp;фотографиями</h2>`

2022-06-08 11:58 UTC, Stern-Ritter commented on index.html
> +        <h2 class="photo__title">Заголовок блока с фотографиями</h2>
Наверное лучше неразрывный пробел поставить чтобы было как в макете с переносом 
`<h2 class="photo__title">Заголовок блока с&nbsp;фотографиями</h2>`

2022-06-08 14:43 UTC, IIKolchin commented on index.html
> +      <section class="card">
да тут вообще лучше так сделать:
<body class="page">
<header class-"header"> и т.д.

2022-06-08 14:47 UTC, IIKolchin commented on blocks/card/__title/card__title.css
> +  cursor: pointer;
там же кнопки выезжают при наведении, можно конечно без pointer

2022-06-13 19:06 UTC, Stern-Ritter approved these changes

2022-06-13 19:20 UTC, merged